#forms
aspect.push "INFO"
aspect.push "error"
aspect.push "client-error"
aspect.push "server-error"
aspect.push "install"

#aspect.push "geoloc"
#aspect.push "trips-filter"
#aspect.push "trips-drawing"
#aspect.push "stops-drawing"
#aspect.push "admin-stops"
#aspect.push "data-publish"
#aspect.push "trip-publish"
#aspect.push "one-trip-publish"
#aspect.push "own-trip-publish"

#aspect.push "trip-crud"
aspect.push "trips-matcher"
#aspect.push "trip-request"
#aspect.push "read-trip"
#aspect.push "trips-drawing"
#aspect.push "carpool-api"
#aspect.push "trip-notifications"
#aspect.push  "notifications"

#aspect.push "chat"
