export const LOCATION_FROM_UPDATED = 'LOCATION_FROM_UPDATED';
export const LOCATION_TO_UPDATED = 'LOCATION_TO_UPDATED';
export const DATETIME_UPDATED = 'DATETIME_UPDATED';
export const USER_LOCATION_DETECTED = 'USER_LOCATION_DETECTED';
